version: "3.8"
services:
  server:
    build: ./server
    restart: on-failure
    ports:
      - 7272:7272
    volumes:
      - ./server:/app
      - /app/node_modules
      - logs:/app/logs
  front:
    build: ./frontendSO
    restart: on-failure
    ports:
      - 7172:7172
    volumes:
      - ./frontendSO:/app
      - /app/node_modules
      - logs:/app/logs

volumes:
  logs: